# Generated by Django 4.1.5 on 2023-02-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='pic',
            field=models.FileField(default='default.png', upload_to='profile_pics'),
        ),
    ]
