# Generated by Django 4.1.5 on 2023-02-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='shop_Name',
            new_name='shop_name',
        ),
    ]
