# Generated by Django 4.1.5 on 2023-02-04 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_rename_pic_seller_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('price', models.FloatField(default=1.0)),
                ('product_stock', models.IntegerField(default=0)),
                ('product_pic', models.FileField(default='productdef.png', upload_to='product_pics')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
    ]
