# Generated by Django 4.1.5 on 2023-02-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_rename_myorders_myorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
