# Generated by Django 4.1.5 on 2023-02-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_alter_myorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
